// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { Toaster } from "sonner";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">
//         {children}
//         <Toaster richColors />
//       </body>
//     </html>
//   );
// }


/*
SafeOps Swiss Cybernetics layout direction: IBM Plex Sans and IBM Plex Mono create a precise security-operations tone,
while metadata and global toast behavior frame the app as a production SaaS interface rather than a starter template.
*/

import type { Metadata } from "next";
import type { ReactNode } from "react";
import { IBM_Plex_Mono, IBM_Plex_Sans } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const plexSans = IBM_Plex_Sans({
  variable: "--font-plex-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const plexMono = IBM_Plex_Mono({
  variable: "--font-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "SafeOps | Cloud Security Posture and Remediation",
  description:
    "SafeOps helps startup teams scan AWS, prioritize high-signal cloud risks, and apply supported remediations from a focused SaaS command center.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className={`${plexSans.variable} ${plexMono.variable} h-full scroll-smooth antialiased`}>
      <body className="min-h-full bg-background font-sans text-foreground">
        {children}
        <Toaster richColors position="top-right" toastOptions={{ duration: 4200 }} />
      </body>
    </html>
  );
}
